[pytest]
testpaths = backend/tests tests
asyncio_mode = auto
filterwarnings =
    ignore::PendingDeprecationWarning:starlette.*
    ignore:The 'app' shortcut is now deprecated.*:DeprecationWarning:httpx.*
    ignore::ResourceWarning:sqlalchemy.*
    ignore::ResourceWarning:anyio.*
    ignore::ResourceWarning:asyncio.*
    ignore::ResourceWarning:unittest.*
    ignore:.*unclosed database.*:ResourceWarning
    ignore:.*unclosed event loop.*:ResourceWarning
    ignore:.*Unclosed <MemoryObject.*:ResourceWarning
    ignore:.*unclosed transport.*:ResourceWarning
    ignore::pytest.PytestReturnNotNoneWarning
    ignore:Identity map already had.*:sqlalchemy.exc.SAWarning
