# Alembic configuration file.

[alembic]
# path to migration scripts
sqlalchemy.url = sqlite:///./tradingbot.db
script_location = alembic
sqlversion_location = 
file_template = %%(rev)s_%%(slug)s
date_format = %%(rev)s_%%(epoch)s
revision_file_template = %%(rev)s_%%(slug)s

# Logging configuration
[loggers]
keys = root,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
