"""initial schema

Revision ID: 51c2bc15c671
Revises: 
Create Date: 2026-04-16 21:47:58.657653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '51c2bc15c671'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables if they exist
    with op.get_context().autocommit_block():
        try:
            op.drop_table('backtest_trades')
        except Exception:
            print("Skipped: 'backtest_trades' table does not exist.")
        try:
            op.drop_table('backtest_runs')
        except Exception:
            print("Skipped: 'backtest_runs' table does not exist.")
    # Create index if not exists
    with op.get_context().autocommit_block():
        try:
            op.create_index(op.f('ix_ai_logs_call_type'), 'ai_logs', ['call_type'], unique=False)
        except Exception:
            print("Skipped: 'ix_ai_logs_call_type' index already exists.")
    # Create index if not exists
    with op.get_context().autocommit_block():
        try:
            op.create_index(op.f('ix_ai_logs_id'), 'ai_logs', ['id'], unique=False)
        except Exception:
            print("Skipped: 'ix_ai_logs_id' index already exists.")
    # Create index if not exists
    with op.get_context().autocommit_block():
        try:
            op.create_index(op.f('ix_ai_logs_provider'), 'ai_logs', ['provider'], unique=False)
        except Exception:
            print("Skipped: 'ix_ai_logs_provider' index already exists.")
    # Create index if not exists
    with op.get_context().autocommit_block():
        try:
            op.create_index(op.f('ix_ai_logs_timestamp'), 'ai_logs', ['timestamp'], unique=False)
        except Exception:
            print("Skipped: 'ix_ai_logs_timestamp' index already exists.")
    # Create index if not exists
    with op.get_context().autocommit_block():
        try:
            op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
        except Exception:
            print("Skipped: 'ix_audit_log_id' index already exists.")
    # SQLite does not support ALTER COLUMN; skipping for SQLite
    if op.get_bind().dialect.name != 'sqlite':
        op.alter_column('bot_state', 'testnet_trades',
                   existing_type=sa.FLOAT(),
                   type_=sa.Integer(),
                   existing_nullable=True,
                   existing_server_default=sa.text('(0.0)'))
    else:
        print("Skipped: ALTER COLUMN 'testnet_trades' unsupported in SQLite.")
    # SQLite does not support ALTER COLUMN; skipping for SQLite
    if op.get_bind().dialect.name != 'sqlite':
        op.alter_column('bot_state', 'testnet_wins',
                   existing_type=sa.FLOAT(),
                   type_=sa.Integer(),
                   existing_nullable=True,
                   existing_server_default=sa.text('(0.0)'))
    else:
        print("Skipped: ALTER COLUMN 'testnet_wins' unsupported in SQLite.")
    # Create index if not exists
    with op.get_context().autocommit_block():
        try:
            op.create_index(op.f('ix_bot_state_active_wallet'), 'bot_state', ['active_wallet'], unique=False)
        except Exception:
            print("Skipped: 'ix_bot_state_active_wallet' index already exists.")
    # SQLite does not support DROP COLUMN; skipping if column does not exist
    if op.get_bind().dialect.name != 'sqlite':
        with op.get_context().autocommit_block():
            try:
                op.drop_column('bot_state', 'live_bankroll')
            except Exception:
                print("Skipped: 'live_bankroll' column does not exist.")
    else:
        print("Skipped: DROP COLUMN 'live_bankroll' unsupported in SQLite.")
    # SQLite does not support DROP COLUMN; skipping if column does not exist
    if op.get_bind().dialect.name != 'sqlite':
        with op.get_context().autocommit_block():
            try:
                op.drop_column('bot_state', 'track_bankroll_whale')
            except Exception:
                print("Skipped: 'track_bankroll_whale' column does not exist.")
    else:
        print("Skipped: DROP COLUMN 'track_bankroll_whale' unsupported in SQLite.")
    op.drop_column('bot_state', 'live_trades')
    op.drop_column('bot_state', 'track_pnl_realtime')
    op.drop_column('bot_state', 'track_loss_limit_commodity')
    op.drop_column('bot_state', 'track_pnl_whale')
    op.drop_column('bot_state', 'track_pnl_commodity')
    op.drop_column('bot_state', 'track_bankroll_realtime')
    op.drop_column('bot_state', 'track_loss_limit_realtime')
    op.drop_column('bot_state', 'live_wins')
    op.drop_column('bot_state', 'track_bankroll_commodity')
    op.drop_column('bot_state', 'live_pnl')
    op.drop_column('bot_state', 'track_loss_limit_whale')
    op.create_index(op.f('ix_btc_price_snapshots_id'), 'btc_price_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_btc_price_snapshots_timestamp'), 'btc_price_snapshots', ['timestamp'], unique=False)
    op.alter_column('copy_trader_entries', 'pnl',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.create_index(op.f('ix_copy_trader_entries_wallet'), 'copy_trader_entries', ['wallet'], unique=False)
    op.create_index(op.f('ix_decision_log_created_at'), 'decision_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_decision_log_id'), 'decision_log', ['id'], unique=False)
    op.create_index(op.f('ix_decision_log_market_ticker'), 'decision_log', ['market_ticker'], unique=False)
    op.create_index(op.f('ix_decision_log_strategy'), 'decision_log', ['strategy'], unique=False)
    op.create_index('idx_job_queue_status_priority', 'job_queue', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_job_queue_id'), 'job_queue', ['id'], unique=False)
    op.create_index(op.f('ix_market_watch_id'), 'market_watch', ['id'], unique=False)
    op.create_index(op.f('ix_market_watch_ticker'), 'market_watch', ['ticker'], unique=True)
    op.drop_index(op.f('ix_pending_approvals_status'), table_name='pending_approvals')
    op.create_index(op.f('ix_pending_approvals_market_id'), 'pending_approvals', ['market_id'], unique=False)
    op.create_index(op.f('ix_scan_logs_id'), 'scan_logs', ['id'], unique=False)
    op.create_index(op.f('ix_scan_logs_run_id'), 'scan_logs', ['run_id'], unique=True)
    op.drop_index(op.f('ix_settlement_events_trade_id'), table_name='settlement_events')
    op.create_index(op.f('ix_settlement_events_market_ticker'), 'settlement_events', ['market_ticker'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_market_ticker'), 'signals', ['market_ticker'], unique=False)
    op.create_index(op.f('ix_signals_market_type'), 'signals', ['market_type'], unique=False)
    op.create_index(op.f('ix_signals_timestamp'), 'signals', ['timestamp'], unique=False)
    op.create_index(op.f('ix_signals_track_name'), 'signals', ['track_name'], unique=False)
    op.create_index(op.f('ix_strategy_config_id'), 'strategy_config', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_config_strategy_name'), 'strategy_config', ['strategy_name'], unique=True)
    op.alter_column('trades', 'filled_size',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('trades', 'clob_idempotency_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_trades_settled_mode'), table_name='trades')
    op.drop_index(op.f('ix_trades_ticker_settled'), table_name='trades')
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_market_end_date'), 'trades', ['market_end_date'], unique=False)
    op.create_index(op.f('ix_trades_market_ticker'), 'trades', ['market_ticker'], unique=False)
    op.create_index(op.f('ix_trades_market_type'), 'trades', ['market_type'], unique=False)
    op.create_index(op.f('ix_trades_signal_id'), 'trades', ['signal_id'], unique=False)
    op.create_index(op.f('ix_trades_trading_mode'), 'trades', ['trading_mode'], unique=False)
    op.create_foreign_key(None, 'trades', 'signals', ['signal_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_wallet_config_address'), 'wallet_config', ['address'], unique=True)
    op.create_index(op.f('ix_wallet_config_id'), 'wallet_config', ['id'], unique=False)
    op.create_index(op.f('ix_whale_transactions_market_id'), 'whale_transactions', ['market_id'], unique=False)
    op.create_index(op.f('ix_whale_transactions_tx_hash'), 'whale_transactions', ['tx_hash'], unique=True)
    op.create_index(op.f('ix_whale_transactions_wallet'), 'whale_transactions', ['wallet'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whale_transactions_wallet'), table_name='whale_transactions')
    op.drop_index(op.f('ix_whale_transactions_tx_hash'), table_name='whale_transactions')
    op.drop_index(op.f('ix_whale_transactions_market_id'), table_name='whale_transactions')
    op.drop_index(op.f('ix_wallet_config_id'), table_name='wallet_config')
    op.drop_index(op.f('ix_wallet_config_address'), table_name='wallet_config')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_index(op.f('ix_trades_trading_mode'), table_name='trades')
    op.drop_index(op.f('ix_trades_signal_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_market_type'), table_name='trades')
    op.drop_index(op.f('ix_trades_market_ticker'), table_name='trades')
    op.drop_index(op.f('ix_trades_market_end_date'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.create_index(op.f('ix_trades_ticker_settled'), 'trades', ['market_ticker', 'settled'], unique=False)
    op.create_index(op.f('ix_trades_settled_mode'), 'trades', ['settled', 'trading_mode'], unique=False)
    op.alter_column('trades', 'clob_idempotency_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('trades', 'filled_size',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_strategy_config_strategy_name'), table_name='strategy_config')
    op.drop_index(op.f('ix_strategy_config_id'), table_name='strategy_config')
    op.drop_index(op.f('ix_signals_track_name'), table_name='signals')
    op.drop_index(op.f('ix_signals_timestamp'), table_name='signals')
    op.drop_index(op.f('ix_signals_market_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_market_ticker'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index(op.f('ix_settlement_events_market_ticker'), table_name='settlement_events')
    op.create_index(op.f('ix_settlement_events_trade_id'), 'settlement_events', ['trade_id'], unique=False)
    op.drop_index(op.f('ix_scan_logs_run_id'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_logs_id'), table_name='scan_logs')
    op.drop_index(op.f('ix_pending_approvals_market_id'), table_name='pending_approvals')
    op.create_index(op.f('ix_pending_approvals_status'), 'pending_approvals', ['status'], unique=False)
    op.drop_index(op.f('ix_market_watch_ticker'), table_name='market_watch')
    op.drop_index(op.f('ix_market_watch_id'), table_name='market_watch')
    op.drop_index(op.f('ix_job_queue_id'), table_name='job_queue')
    op.drop_index('idx_job_queue_status_priority', table_name='job_queue')
    op.drop_index(op.f('ix_decision_log_strategy'), table_name='decision_log')
    op.drop_index(op.f('ix_decision_log_market_ticker'), table_name='decision_log')
    op.drop_index(op.f('ix_decision_log_id'), table_name='decision_log')
    op.drop_index(op.f('ix_decision_log_created_at'), table_name='decision_log')
    op.drop_index(op.f('ix_copy_trader_entries_wallet'), table_name='copy_trader_entries')
    op.alter_column('copy_trader_entries', 'pnl',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.drop_index(op.f('ix_btc_price_snapshots_timestamp'), table_name='btc_price_snapshots')
    op.drop_index(op.f('ix_btc_price_snapshots_id'), table_name='btc_price_snapshots')
    op.add_column('bot_state', sa.Column('track_loss_limit_whale', sa.FLOAT(), server_default=sa.text('(50.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('live_pnl', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_bankroll_commodity', sa.FLOAT(), server_default=sa.text('(100.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('live_wins', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_loss_limit_realtime', sa.FLOAT(), server_default=sa.text('(50.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_bankroll_realtime', sa.FLOAT(), server_default=sa.text('(100.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_pnl_commodity', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_pnl_whale', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_loss_limit_commodity', sa.FLOAT(), server_default=sa.text('(50.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_pnl_realtime', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('live_trades', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_bankroll_whale', sa.FLOAT(), server_default=sa.text('(100.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('live_bankroll', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
    op.drop_index(op.f('ix_bot_state_active_wallet'), table_name='bot_state')
    op.alter_column('bot_state', 'testnet_wins',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('bot_state', 'testnet_trades',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_ai_logs_timestamp'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_provider'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_call_type'), table_name='ai_logs')
    op.create_table('backtest_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('strategy_name', sa.VARCHAR(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('initial_bankroll', sa.FLOAT(), nullable=False),
    sa.Column('params', sqlite.JSON(), nullable=True),
    sa.Column('final_equity', sa.FLOAT(), nullable=False),
    sa.Column('total_pnl', sa.FLOAT(), nullable=False),
    sa.Column('total_return_pct', sa.FLOAT(), nullable=False),
    sa.Column('win_rate', sa.FLOAT(), nullable=False),
    sa.Column('total_trades', sa.INTEGER(), nullable=False),
    sa.Column('winning_trades', sa.INTEGER(), nullable=False),
    sa.Column('losing_trades', sa.INTEGER(), nullable=False),
    sa.Column('sharpe_ratio', sa.FLOAT(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_trades',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('signal_id', sa.INTEGER(), nullable=True),
    sa.Column('market_ticker', sa.VARCHAR(), nullable=False),
    sa.Column('platform', sa.VARCHAR(), nullable=False),
    sa.Column('direction', sa.VARCHAR(), nullable=False),
    sa.Column('entry_price', sa.FLOAT(), nullable=False),
    sa.Column('exit_price', sa.FLOAT(), nullable=True),
    sa.Column('size', sa.FLOAT(), nullable=False),
    sa.Column('pnl', sa.FLOAT(), nullable=False),
    sa.Column('result', sa.VARCHAR(), nullable=False),
    sa.Column('edge_at_entry', sa.FLOAT(), nullable=False),
    sa.Column('market_probability_at_entry', sa.FLOAT(), nullable=True),
    sa.Column('model_probability_at_entry', sa.FLOAT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('executed', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
