"""add mode column to bot_state as composite primary key

Revision ID: cd91e4066413
Revises: b8c3dbb47949
Create Date: 2026-04-19 03:46:45.930863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cd91e4066413'
down_revision: Union[str, Sequence[str], None] = 'b8c3dbb47949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Minimal migration: only add fee and slippage columns to trades table
    try:
        op.add_column('trades', sa.Column('fee', sa.Float(), nullable=True))
    except Exception:
        pass  # Column may already exist
    try:
        op.add_column('trades', sa.Column('slippage', sa.Float(), nullable=True))
    except Exception:
        pass  # Column may already exist


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_trades_ticker_settled'), 'trades', ['market_ticker', 'settled'], unique=False)
    op.create_index(op.f('ix_trades_settled_mode'), 'trades', ['settled', 'trading_mode'], unique=False)
    op.create_index(op.f('idx_trades_source'), 'trades', ['source'], unique=False)
    op.create_index(op.f('idx_trades_last_sync_at'), 'trades', ['last_sync_at'], unique=False)
    op.create_index(op.f('idx_trades_clob_order_id'), 'trades', ['clob_order_id'], unique=False)
    op.create_index(op.f('idx_trades_blockchain_verified'), 'trades', ['blockchain_verified'], unique=False)
    op.drop_column('trades', 'slippage')
    op.drop_column('trades', 'fee')
    op.alter_column('strategy_config', 'mode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('ix_settlement_events_trade_id'), 'settlement_events', ['trade_id'], unique=False)
    op.create_index(op.f('ix_pending_approvals_status'), 'pending_approvals', ['status'], unique=False)
    op.add_column('bot_state', sa.Column('track_pnl_whale', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_loss_limit_commodity', sa.FLOAT(), server_default=sa.text('(50.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_bankroll_whale', sa.FLOAT(), server_default=sa.text('(100.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_loss_limit_realtime', sa.FLOAT(), server_default=sa.text('(50.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_bankroll_realtime', sa.FLOAT(), server_default=sa.text('(100.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_pnl_realtime', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_bankroll_commodity', sa.FLOAT(), server_default=sa.text('(100.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_loss_limit_whale', sa.FLOAT(), server_default=sa.text('(50.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_pnl_commodity', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_column('audit_log', 'user_id')
    op.drop_column('audit_log', 'new_value')
    op.drop_column('audit_log', 'old_value')
    op.drop_column('audit_log', 'entity_id')
    op.drop_column('audit_log', 'entity_type')
    op.drop_column('audit_log', 'event_type')
    op.create_table('backtest_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('strategy_name', sa.VARCHAR(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('initial_bankroll', sa.FLOAT(), nullable=False),
    sa.Column('params', sqlite.JSON(), nullable=True),
    sa.Column('final_equity', sa.FLOAT(), nullable=False),
    sa.Column('total_pnl', sa.FLOAT(), nullable=False),
    sa.Column('total_return_pct', sa.FLOAT(), nullable=False),
    sa.Column('win_rate', sa.FLOAT(), nullable=False),
    sa.Column('total_trades', sa.INTEGER(), nullable=False),
    sa.Column('winning_trades', sa.INTEGER(), nullable=False),
    sa.Column('losing_trades', sa.INTEGER(), nullable=False),
    sa.Column('sharpe_ratio', sa.FLOAT(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_strategy_name'), 'backtest_runs', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_backtest_runs_id'), 'backtest_runs', ['id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('signal_id', sa.INTEGER(), nullable=True),
    sa.Column('market_ticker', sa.VARCHAR(), nullable=False),
    sa.Column('platform', sa.VARCHAR(), nullable=False),
    sa.Column('direction', sa.VARCHAR(), nullable=False),
    sa.Column('entry_price', sa.FLOAT(), nullable=False),
    sa.Column('exit_price', sa.FLOAT(), nullable=True),
    sa.Column('size', sa.FLOAT(), nullable=False),
    sa.Column('pnl', sa.FLOAT(), nullable=False),
    sa.Column('result', sa.VARCHAR(), nullable=False),
    sa.Column('edge_at_entry', sa.FLOAT(), nullable=False),
    sa.Column('market_probability_at_entry', sa.FLOAT(), nullable=True),
    sa.Column('model_probability_at_entry', sa.FLOAT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('executed', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_run_id'), 'backtest_trades', ['run_id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_id'), 'backtest_trades', ['id'], unique=False)
    # ### end Alembic commands ###
